### ISSUE TITLE
_liquidate function in loan contracts set escrow collateral recipient as msg.sender 

### ISSUE THREAD

**Issue by James-Sangalli** [debtdao/smart-contracts#51]
This is an internal function and will cause the funds to go to the loan contract instead of the arbiter or the address the arbiters wants to send the funds. 

Example: https://github.com/debtdao/smart-contracts/blob/master/contracts/modules/loan/EscrowedLoan.sol#L34

**Comment by kibagateaux** [comment]
this isn't in the `Escrow` contract, `EscrowedLoan` is inherited by (so is itself) the Loan contract  meaning `msg.sender` would still be arbiter wouldn't it?

**Comment by James-Sangalli** [comment]
> this isn't in the `Escrow` contract, `EscrowedLoan` is inherited by (so is itself) the Loan contract meaning `msg.sender` would still be arbiter wouldn't it?

Apologies, I confused myself over whether the fund returning address should be the arbiter or not and whether msg.sender would be preserved if it was called via an internal function. 

I validated the assumption on remix and msg.sender was preserved, it would therefore remain as the arbiter.
